export default
{
  CHANGE_LOGIN_STATUS: 'backend/CHANGE_LOGIN_STATUS',
  SET_CREATE_USER_EMAIL_ERROR: 'backend/SET_CRATE_USER_EMAIL_ERROR',
  SET_CREATE_USER_PASSWORD_ERROR: 'backend/SET_CREATE_USER_PASSWORD_ERROR',
  SET_CREATE_USER_GENERAL_ERROR: 'backend/SET_CREATE_USER_GENERAL_ERROR',
  CLEAR_ERRORS: 'backend/CLEAR_ERRORS',
};
